# Generated by Django 3.0.5 on 2022-11-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_orders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
