# Generated by Django 3.0.5 on 2022-11-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_auto_20221115_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
