# Generated by Django 4.1.3 on 2022-11-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_rename_order_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_buycount',
            new_name='p_stock',
        ),
        migrations.RemoveField(
            model_name='category',
            name='c_created_at',
        ),
        migrations.AlterField(
            model_name='review',
            name='r_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
