# Generated by Django 4.1.3 on 2022-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_alter_orders_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
